version: '3.7'

services:
  db:
    image: mariadb
    container_name: nextcloud_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: password
    volumes:
      - db:/var/lib/mysql

  app:
    image: nextcloud
    container_name: nextcloud_app
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - ./app:/var/www/html
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: password
      NEXTCLOUD_TRUSTED_DOMAIN: localhost
      NEXTCLOUD_INSTANCE_ID: OucjtW2QNxJ3MCVs
      NEXTCLOUD_PASSWORD_SALT: zgg+DTZA26HEA8qL7a+b7wNx9WHzVaPl4VAnbzhx24o=
      NEXTCLOUD_SECRET: +KyDr+VYxumAIfRmnMW47LUEL9K3XZ9XGe1xHmINCMhMmU5gv/Yqjwu4r2Gu2xnvyTPAW2Lkm8WwXPQZi3hqg==
    depends_on:
      - db

volumes:
  db:
