name: Build and Deploy
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout                    # Check out code
        uses: actions/checkout@v4
      - name: Rename file                 # rename prod config file
        run: mv app/config/config-prod.php app/config/config.php  
      - name: Delete file                 # delete dev config file
        run: rm app/config/config-dev.php
      - name: Upload artifact             # upload
        uses: actions/upload-artifact@v4  
        with:
          name: app
          path: |
            app
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app
      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete --exclude='data/' --chown=www-data:www-data
          path: .
          remote_path: /var/www/nextcloud
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}